CREATE sequence ACCOUNT_SEQ;
CREATE sequence CUSTOMER_SEQ;
CREATE sequence FLOWER_SEQ;
CREATE sequence STOCK_SEQ;



CREATE TABLE "ACCOUNT"
(
    "ID" NUMBER(10,0) PRIMARY KEY,
    "LOGIN" VARCHAR2(45 CHAR) NOT NULL,
    "PASSWORD" VARCHAR2(45 CHAR) NOT NULL,
    "TYPE" VARCHAR2(1 CHAR) NOT NULL
);

Insert into ACCOUNT (ID, LOGIN,PASSWORD,TYPE) values (ACCOUNT_SEQ.NEXTVAL, 'admin','admin123','A');
Insert into ACCOUNT (ID, LOGIN,PASSWORD,TYPE) values (ACCOUNT_SEQ.NEXTVAL, 'eaglesss','qwerty','C');
Insert into ACCOUNT (ID, LOGIN,PASSWORD,TYPE) values (ACCOUNT_SEQ.NEXTVAL, 'oops','123456','C');



CREATE TABLE "CUSTOMER"
(
    "ID" NUMBER(10,0) PRIMARY KEY,
    "ACCOUNT_ID" NUMBER(10,0) NOT NULL,
    "FIRST_NAME" VARCHAR2(45 CHAR) NOT NULL,
    "MIDDLE_NAME" VARCHAR2(45 CHAR) NOT NULL,
    "LAST_NAME" VARCHAR2(45 CHAR) NOT NULL,
    "E_MAIL" VARCHAR2(45 CHAR) NOT NULL,
    "PHONE_NUMBER" NUMBER(11, 0) NOT NULL,
    "MONEY" NUMBER(9, 2) NOT NULL,
    "DISCOUNT" NUMBER(2) NOT NULL
);

Insert into CUSTOMER (ID, ACCOUNT_ID, FIRST_NAME, MIDDLE_NAME, LAST_NAME, E_MAIL, PHONE_NUMBER, MONEY, DISCOUNT) values (CUSTOMER_SEQ.NEXTVAL, 2, 'Nikita','Aleksandrovich','Orlov', 'agamon@mail.ru', 89201542335, 100000.00, 10);
Insert into CUSTOMER (ID, ACCOUNT_ID, FIRST_NAME, MIDDLE_NAME, LAST_NAME, E_MAIL, PHONE_NUMBER, MONEY, DISCOUNT) values (CUSTOMER_SEQ.NEXTVAL, 3, 'Nikita','Igorevich','Popov', 'boooo@rambler.ru', 89209984445, 100.00, 1);



CREATE TABLE "FLOWER"
(
    "ID" NUMBER(10,0) PRIMARY KEY,
    "NAME" VARCHAR2(45 CHAR) NOT NULL,
    "COST" NUMBER(8, 2) NOT NULL,
);

Insert into FLOWER (ID, NAME, COST) values (FLOWER_SEQ.NEXTVAL, 'Chamomile', 10.00);
Insert into FLOWER (ID, NAME, COST) values (FLOWER_SEQ.NEXTVAL, 'Jasmine', 50.00);
Insert into FLOWER (ID, NAME, COST) values (FLOWER_SEQ.NEXTVAL, 'Chrysanthemums', 66.13);
Insert into FLOWER (ID, NAME, COST) values (FLOWER_SEQ.NEXTVAL, 'Lilac', 23.42);
Insert into FLOWER (ID, NAME, COST) values (FLOWER_SEQ.NEXTVAL, 'Tulips', 90.00);
Insert into FLOWER (ID, NAME, COST) values (FLOWER_SEQ.NEXTVAL, 'Lotus', 141.50);
Insert into FLOWER (ID, NAME, COST) values (FLOWER_SEQ.NEXTVAL, 'Roses', 115.00);



CREATE TABLE "STOCK"
(
    "ID" NUMBER(10,0) PRIMARY KEY,
    "FLOWER_ID" NUMBER(10,0) NOT NULL,
    "FLOWER_COUNT" NUMBER(8, 0) NOT NULL,
);

Insert into STOCK (ID, FLOWER_ID, FLOWER_COUNT) values (STOCK_SEQ.NEXTVAL, 1, 0);
Insert into STOCK (ID, FLOWER_ID, FLOWER_COUNT) values (STOCK_SEQ.CURVAL, 2, 105);
Insert into STOCK (ID, FLOWER_ID, FLOWER_COUNT) values (STOCK_SEQ.CURVAL, 3, 266);
Insert into STOCK (ID, FLOWER_ID, FLOWER_COUNT) values (STOCK_SEQ.CURVAL, 4, 95);
Insert into STOCK (ID, FLOWER_ID, FLOWER_COUNT) values (STOCK_SEQ.CURVAL, 5, 576);
Insert into STOCK (ID, FLOWER_ID, FLOWER_COUNT) values (STOCK_SEQ.CURVAL, 6, 395);
Insert into STOCK (ID, FLOWER_ID, FLOWER_COUNT) values (STOCK_SEQ.CURVAL, 7, 976);

Insert into STOCK (ID, FLOWER_ID, FLOWER_COUNT) values (STOCK_SEQ.NEXTVAL, 1, 810);
Insert into STOCK (ID, FLOWER_ID, FLOWER_COUNT) values (STOCK_SEQ.CURVAL, 2, 311);
Insert into STOCK (ID, FLOWER_ID, FLOWER_COUNT) values (STOCK_SEQ.CURVAL, 3, 1625);
Insert into STOCK (ID, FLOWER_ID, FLOWER_COUNT) values (STOCK_SEQ.CURVAL, 4, 6234);
Insert into STOCK (ID, FLOWER_ID, FLOWER_COUNT) values (STOCK_SEQ.CURVAL, 5, 0);
Insert into STOCK (ID, FLOWER_ID, FLOWER_COUNT) values (STOCK_SEQ.CURVAL, 6, 1132);
Insert into STOCK (ID, FLOWER_ID, FLOWER_COUNT) values (STOCK_SEQ.CURVAL, 7, 5815);


